### ISSUE TITLE
Digital Read from motor?

### ISSUE THREAD

**Issue by malk0lm** [arduino-libraries/MKRMotorCarrier#12]
I have a motor that is controlled by a photo interrupter, but I don't see a way to connect it to the Motor Carrier board to work as an interrupt or other logic.

Any advice?

Thanks!

**Comment by ErnestoELC** [comment]
Hi malk0lm,
The MKRMotorCarrier have 4 ports (labeled IN1, IN2, IN3, IN4) that connects to analog inputs of the MKR1000, including A1(IN2) and A2(IN4) that you can use as interrupts. 

Hope this helps!

**Comment by malk0lm** [comment]
Thanks, I will try that out!
