### ISSUE TITLE
Add servo attach and detach feature

### ISSUE THREAD

**Issue by madhugovindarajan** [arduino-libraries/MKRMotorCarrier#5]
User requested the following - "Without the capability to detach a servo, it keeps humming with a low noise even when it is not being used. "

**Comment by facchinm** [comment]
Fixed with https://github.com/arduino-libraries/MKRMotorCarrier/blob/bef98d59f01535472de0ea10580390f49a2a448d/src/ServoMotor.cpp#L31 and https://github.com/arduino-libraries/MKRMotorCarrier/blob/bef98d59f01535472de0ea10580390f49a2a448d/extras/D11-Firmware/ServoMotor.cpp#L6
